IMG_PATH = './test.jpg'
SEED = None
RES_SCALE = 0.4
DOWNSAMPLING_FACTOR = 3
PARALLELIZATION = True

N_OBJECTS = 10000
ROUNDS_PER_STEP = 1
ITERATIONS = 2

SAVE_TOP_RATIO = 0.2
MUTATION_CHANCE = 0.8
MUTATION_RATE = 0.1
CROWD_SIZE = 5
