IMG_PATH = './test.jpg'
SEED = None
ANTIALIASING = True
RES_SCALE = 0.3
DOWNSAMPLING_FACTOR = 5
PARALLELIZATION = True

N_OBJECTS = 1000
ROUNDS_PER_STEP = 5
FIT_CHECK = True
ITERATIONS = 100

SAVE_TOP_RATIO = 0.2
MUTATION_CHANCE = 0.8
MUTATION_RATE = 0.1
CROWD_SIZE = 5
